# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fb8a361234becb7f040e3b57174a25574356f5e1ff350f44c77bacde0b3e6a84962bced6d41c4e343f3b9a6426cda02ce068d3dcd2711fb2f637e4d1e6347ed

test:
  secret_key_base: b8ff1dabcb844181a317a7553841450465b086da0ab9327eea0313ccd4dd7cdc19c62b10300ff2d7f0605811df3f063b70eab1bd876b1532a404e93e749f4a0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
